/** @jsxImportSource @zen/tui */
/**
 * Zen TUI Chatbot Demo
 *
 * Showcases all TUI features in a chatbot interface.
 * Run with: bun run src/chatbot-demo.tsx
 */

import { signal } from '@zen/signal';
import {
  Badge, Box, Divider, FocusProvider, Markdown, Spinner, Text, TextInput, ToastContainer, type TreeNode, TreeView, toast, useInput, render, FullscreenLayout } from '@zen/tui';

// Sample data
const COMMANDS = ['/help', '/clear', '/files', '/model'];

const FILE_TREE: TreeNode[] = [
  {
    id: 'src', label: 'src', icon: '📁', defaultExpanded: true, children: [
      { id: 'app', label: 'App.tsx', icon: '⚛️' }, { id: 'main', label: 'main.ts', icon: '📄' }, ]}, { id: 'pkg', label: 'package.json', icon: '📋' }, ];

function ChatbotDemo() {
  const inputValue = signal('');
  const showFiles = signal(false);
  const isTyping = signal(false);
  const model = signal('claude-3.5-sonnet');
  const tokens = signal(0);
  const lastResponse = signal(`# Welcome to Zen TUI! 🤖

This demo showcases **all features**:

- \`TextInput\` with autocomplete (type \`/\`)
- **Markdown** rendering
- TreeView (try \`/files\`)
- Toast notifications
- Spinner animation

**Try these commands:**
- \`/help\` - Show help
- \`/files\` - Toggle file browser
- \`/model\` - Switch AI model
- \`/clear\` - Clear display`);

  const getSuggestions = (val: string) => {
    if (!val.startsWith('/')) return [];
    return COMMANDS.filter((c) => c.startsWith(val)).slice(0, 3); // Max 3 suggestions
  };

  // Simulate streaming text
  const streamText = (fullText: string, onComplete: () => void) => {
    let index = 0;
    const words = fullText.split(' ');

    const streamInterval = setInterval(() => {
      if (index < words.length) {
        lastResponse.value =
          words.slice(0, index + 1).join(' ') + (index < words.length - 1 ? ' ▌' : '');
        index++;
        tokens.value += 2;
      } else {
        clearInterval(streamInterval);
        lastResponse.value = fullText;
        onComplete();
      }
    }, 50);
  };

  const sendMessage = (content: string) => {
    if (!content.trim()) return;

    if (content.startsWith('/')) {
      switch (content) {
        case '/help':
          toast.info('Commands: /clear, /files, /model');
          break;
        case '/clear':
          lastResponse.value = '_Chat cleared_';
          toast.success('Cleared!');
          break;
        case '/files':
          showFiles.value = !showFiles.value;
          toast.info(showFiles.value ? 'Files visible' : 'Files hidden');
          break;
        case '/model': {
          const models = ['claude-3.5-sonnet', 'gpt-4o', 'llama-3'];
          const i = models.indexOf(model.value);
          model.value = models[(i + 1) % models.length];
          toast.success(`Model: ${model.value}`);
          break;
        }
        default:
          toast.warning(`Unknown: ${content}`);
      }
      inputValue.value = '';
      return;
    }

    // User message
    tokens.value += content.length;
    lastResponse.value = `**You:** ${content}\n\n---\n\n`;
    inputValue.value = '';

    // Fake AI response with streaming
    isTyping.value = true;
    setTimeout(() => {
      isTyping.value = false;
      const response = `**You:** ${content.slice(0, 30)}${content.length > 30 ? '...' : ''}\n\n---\n\n## Response\n\nGreat question! Here's my analysis:\n\n- First key point with \`code\`\n- Second observation\n- **Important** conclusion\n\n> Generated by Zen TUI!`;
      streamText(response, () => {
        toast.success('Done!');
      });
    }, 800);
  };

  useInput((input, key) => {
    if (key.ctrl && input === 'l') {
      lastResponse.value = '_Cleared_';
      toast.success('Cleared!');
    }
  });

  // Layout: Use flexbox, NOT manual width calculations!
  // Renderer handles resize automatically when using flex
  const sidebarWidth = 26;

  return (
    <FocusProvider>
      {/* Root: flex: 1 fills available terminal space automatically */}
      <Box style={{ flexDirection: 'column', padding: 1, flex: 1 }}>
        {/* Header */}
        <Box style={{ flexDirection: 'row', justifyContent: 'space-between' }}>
          <Text style={{ bold: true, color: 'cyan' }}>🤖 Zen AI Chatbot</Text>
          <Box style={{ flexDirection: 'row', gap: 1 }}>
            <Badge variant="info">{() => model.value}</Badge>
            <Text style={{ dim: true }}>{() => `${tokens.value} tok`}</Text>
          </Box>
        </Box>
        <Divider />

        {/* Main content row - flex: 1 fills vertical space */}
        {/* Note: Don't use gap here - empty fragments still get gap applied */}
        <Box style={{ flexDirection: 'row', flex: 1 }}>
          {/* Sidebar - use inline conditional for proper TUI rendering */}
          {() =>
            showFiles.value ? (
              <Box
                style={{
                  flexDirection: 'column', width: sidebarWidth, borderStyle: 'single', borderColor: 'gray', padding: 1, marginRight: 1}}
              >
                <Text style={{ bold: true, color: 'yellow' }}>📁 Files</Text>
                <Divider />
                <TreeView nodes={FILE_TREE} onSelect={(n) => toast.info(`Selected: ${n.label}`)} />
              </Box>
            ) : null
          }

          {/* Chat area - flex: 1 fills remaining space automatically */}
          <Box style={{ flexDirection: 'column', flex: 1 }}>
            <Box
              style={{
                flexDirection: 'column', borderStyle: 'round', borderColor: 'cyan', padding: 1, flex: 1}}
            >
              <Text style={{ bold: true, color: 'cyan' }}>🤖 Assistant</Text>
              <Box style={{ paddingLeft: 1 }}>
                <Markdown content={() => lastResponse.value} />
              </Box>
              {/* Typing indicator - use inline conditional */}
              {() =>
                isTyping.value ? (
                  <Box style={{ flexDirection: 'row', gap: 1, marginTop: 1 }}>
                    <Spinner type="dots" color="cyan" />
                    <Text style={{ dim: true }}>Thinking...</Text>
                  </Box>
                ) : null
              }
            </Box>
            <Box style={{ marginTop: 1 }}>
              <TextInput
                id="chat-input"
                value={inputValue}
                placeholder="Type message or /command..."
                suggestions={getSuggestions}
                suggestionsPosition="above"
                maxSuggestions={3}
                onChange={(v) => {
                  inputValue.value = v;
                }}
                onSubmit={sendMessage}
              />
            </Box>
          </Box>
        </Box>

        {/* Footer */}
        <Text style={{ dim: true, marginTop: 1 }}>
          Ctrl+L Clear | /files Files | /model Model | q Quit
        </Text>

        <ToastContainer position="top-right" />
      </Box>
    </FocusProvider>
  );
}

await render(() => (
  <FullscreenLayout>
    <ChatbotDemo />
  </FullscreenLayout>
));
